import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth md:scroll-auto">
      <body className="font-satoshi hide-scrollbar scroll-smooth md:scroll-auto">
        {children}
      </body>
    </html>
  );
}
